Repository hanghae-clone-project/backend_yogiyo_clone, pull requests merged in 2023-01, with the labels that each got.

#4 #3 feature test
  src/main/java/com/yogiyo/clone/YogiyoCloneApplication.java
Labels: documentation

#6 #5 feature test2
  src/main/java/com/yogiyo/clone/YogiyoCloneApplication.java
Labels: documentation

#15 Feature/signup
  .gitignore
  build.gradle
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
  src/main/java/com/yogiyo/clone/domain/user/User.java
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/SignUpForm.java
  src/main/java/com/yogiyo/clone/domain/user/dto/SignUpResponseMessage.java
  src/main/java/com/yogiyo/clone/domain/user/entity/UserRole.java
  src/main/java/com/yogiyo/clone/domain/user/entity/Users.java
  src/main/java/com/yogiyo/clone/domain/user/repository/UserRepository.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
  src/main/java/com/yogiyo/clone/security/UserDetailImpl.java
  src/main/java/com/yogiyo/clone/security/UserDetailServiceImpl.java
  src/main/java/com/yogiyo/clone/security/jwt/JwtAuthFilter.java
  src/main/java/com/yogiyo/clone/security/jwt/JwtUtil.java
  src/main/java/com/yogiyo/clone/security/jwt/dto/SecurityExceptionDto.java
  src/main/resources/application.properties
Labels: 추가기능

#17 Develop #10 #11 어드민 페이지 가게,메뉴 등록 기능 추가
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminApiController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/AdminMenuListResponseDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/AdminMenuResponseDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/MenuAddRequestDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/MenuAddResponseDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/StoreAddRequestDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/StoreAddResponseDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/entity/Store.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/entity/Store_menu.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/repository/AdminApiMenuRepository.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/repository/AdminApiRepository.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/service/AdminApiService.java
  src/main/resources/static/css/login_style.css
  src/main/resources/static/css/signup_style.css
  src/main/resources/static/css/style.css
  src/main/resources/static/images/icon-email.png
  src/main/resources/static/images/icon-lock.png
  src/main/resources/templates/admin_login.html
  src/main/resources/templates/admin_signup.html
Labels: 추가기능

#19 #18 build.gradle thymleaf 빠짐
  build.gradle
Labels: 커밋 실수

#22 Feature/signup
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/SignUpForm.java
  src/main/java/com/yogiyo/clone/domain/user/entity/Users.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
Labels: 추가기능

#27 #26 admin 메인 페이지 추가
  src/main/resources/static/css/admin_main_style.css
  src/main/resources/templates/admin_main.html
Labels: 추가기능

#29 Feature/security
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
Labels: 추가기능

#30 Feature/login
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/LoginForm.java
  src/main/java/com/yogiyo/clone/domain/user/repository/UserRepository.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
Labels: 추가기능

#41 Feature/exception handle
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/SignUpForm.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
  src/main/java/com/yogiyo/clone/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/yogiyo/clone/exception/dto/ExceptionResponseListMessage.java
  src/main/java/com/yogiyo/clone/exception/dto/ExceptionResponseMessage.java
  src/main/java/com/yogiyo/clone/exception/message/ExceptionMessage.java
  src/main/java/com/yogiyo/clone/security/UserDetailsServiceImpl.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
Labels: 추가기능, 테스트코드

#42 TEST #23 로그인 API 테스트
  src/main/java/com/yogiyo/clone/domain/user/entity/Users.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
Labels: 테스트코드

#45 TEST #23 로그인 API 테스트
  build.gradle
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
Labels: 테스트코드

#47 Feature/base entity
  src/main/java/com/yogiyo/clone/config/JpaConfig.java
  src/main/java/com/yogiyo/clone/domain/user/entity/Users.java
  src/main/java/com/yogiyo/clone/security/UserDetailsImpl.java
  src/main/java/com/yogiyo/clone/security/UserDetailsServiceImpl.java
  src/main/java/com/yogiyo/clone/util/Auditor.java
  src/main/java/com/yogiyo/clone/util/BaseEntity.java
  src/main/java/com/yogiyo/clone/util/TimeStamped.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
  src/test/java/com/yogiyo/clone/util/TimeStampedTest.java
Labels: 추가기능, 테스트코드

#49 #44 ADMIN 로그인 연결(JWT 토큰 유지)
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminApiController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/LoginForm.java
  src/main/resources/static/css/admin_main_style.css
  src/main/resources/static/css/login_style.css
  src/main/resources/templates/admin_login.html
  src/main/resources/templates/admin_main.html
  src/main/resources/templates/admin_signup.html
Labels: bug, 추가기능

#53 #50 ADMIN 레이아웃화
  build.gradle
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminController.java
  src/main/resources/static/js/script.js
  src/main/resources/templates/admin_main.html
  src/main/resources/templates/fragments/navigation.html
  src/main/resources/templates/layouts/default_layout.html
  src/main/resources/templates/page/admin_main.html
  src/main/resources/templates/page/admin_main_page.html
  src/main/resources/templates/page/admin_menu_add.html
  src/main/resources/templates/page/admin_order_list.html
  src/main/resources/templates/page/admin_store_detail.html
Labels: bug, 추가기능

#56 Feature/cicd
  .ebextensions/00-makeFiles.config
  .ebextensions/00-set-timezone.config
  .github/workflows/gradle.yml
  .platform/nginx/nginx.conf
  Procfile
  src/main/resources/templates/cors.html
Labels: 추가기능

#57 FEAT #55 CI/CD 테스트 - 스크립트 수정
  .github/workflows/gradle.yml
Labels: 추가기능

#58 Feature/cicd
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
  src/test/java/com/yogiyo/clone/util/TimeStampedTest.java
Labels: 추가기능

#59 FEAT #55 CI/CD 테스트 - 스크립트 수정
  .github/workflows/gradle.yml
Labels: 추가기능

#62 FEAT #55 CI/CD 테스트 - 스크립트 수정
  src/main/java/com/yogiyo/clone/config/WebSecurityConfig.java
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
Labels: 추가기능

#67 FEAT #55 CI/CD 최후통첩.
  .github/workflows/gradle.yml
Labels: 추가기능

#70 #11 ADMIN 페이지 가게 등록 재수정
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminApiController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/entity/Store.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/service/AdminApiService.java
  src/main/java/com/yogiyo/clone/domain/user/entity/Users.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
  src/main/resources/static/js/script.js
Labels: bug

#71 Develop #32 ADMIN 가게 메뉴 추가 페이지 제작
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminApiController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/MenuAddResponseDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/entity/Menu.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/repository/AdminApiMenuRepository.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/repository/AdminApiRepository.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/service/AdminApiService.java
  src/main/resources/static/js/script.js
  src/main/resources/templates/page/admin_menu_add.html
  src/main/resources/templates/page/admin_menu_list.html
Labels: 추가기능

#73 Feature/signup
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/SignUpForm.java
  src/main/java/com/yogiyo/clone/domain/user/repository/UserRepository.java
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
  src/test/java/com/yogiyo/clone/util/TimeStampedTest.java
Labels: 추가기능, 테스트코드

#79 Feature/jwt
  src/main/java/com/yogiyo/clone/security/jwt/JwtAuthFilter.java
  src/main/java/com/yogiyo/clone/security/jwt/JwtUtil.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
  src/test/java/com/yogiyo/clone/security/jwt/JwtAuthFilterTest.java
Labels: 테스트코드

#80 #74 이미지 업로드 S3 연결
  build.gradle
  src/main/java/com/yogiyo/clone/YogiyoCloneApplication.java
  src/main/java/com/yogiyo/clone/config/S3Config.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/controller/AdminImageController.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/dto/FileDto.java
  src/main/java/com/yogiyo/clone/domain/temporary_admin/service/AwsS3Uploader.java
  src/main/resources/static/js/script.js
  src/main/resources/templates/fragments/navigation.html
  src/main/resources/templates/page/admin_menu_add.html
  src/main/resources/templates/page/admin_menu_list.html
  src/main/resources/templates/page/admin_store_add.html
  src/main/resources/templates/page/admin_store_detail.html
Labels: 추가기능

#84 FEAT #80 로그인 API 응답 수정
  src/main/java/com/yogiyo/clone/domain/user/controller/UserController.java
  src/main/java/com/yogiyo/clone/domain/user/dto/LoginResponseMessage.java
Labels: 추가기능

#87 FEAT #86 테스트케이스 데이터베이스 격리
  .github/workflows/gradle.yml
Labels: 추가기능

#89 Feature/test env
  src/main/java/com/yogiyo/clone/domain/user/service/UserService.java
  src/main/java/com/yogiyo/clone/exception/advice/GlobalExceptionHandler.java
  src/test/java/com/yogiyo/clone/domain/user/controller/UserControllerTest.java
  src/test/java/com/yogiyo/clone/security/jwt/JwtAuthFilterTest.java
  src/test/java/com/yogiyo/clone/util/TimeStampedTest.java
Labels: 추가기능

#91 FEAT #90 로그인 오류 수정
  src/main/java/com/yogiyo/clone/security/jwt/JwtAuthFilter.java
Labels: 추가기능
